/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf8ff",
        "secondary-fixed-dim": "#9ecaff",
        "danger-expired": "#DC3545",
        "tertiary": "#6c3400",
        "surface-container-highest": "#e3e1ea",
        "surface-container-high": "#e9e7f0",
        "on-secondary-container": "#00355c",
        "secondary-fixed": "#d1e4ff",
        "inverse-on-surface": "#f2eff9",
        "warning-expiring": "#FFC107",
        "on-surface": "#1a1b22",
        "on-secondary-fixed": "#001d36",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#ffc7a2",
        "surface-variant": "#e3e1ea",
        "outline-variant": "#c5c5d4",
        "primary-container": "#3f51b5",
        "secondary-container": "#33a0fd",
        "secondary": "#0061a4",
        "surface-card": "#FFFFFF",
        "on-surface-variant": "#454652",
        "surface-dim": "#dbd9e2",
        "background": "#fbf8ff",
        "on-background": "#1a1b22",
        "tertiary-fixed-dim": "#ffb784",
        "surface-tint": "#4355b9",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "primary": "#24389c",
        "text-body": "#6C757D",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bac3ff",
        "on-tertiary-fixed-variant": "#713700",
        "text-heading": "#212529",
        "on-error": "#ffffff",
        "outline": "#757684",
        "on-primary-fixed": "#00105c",
        "surface-container": "#efedf6",
        "tertiary-fixed": "#ffdcc6",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#293ca0",
        "surface-page": "#F8F9FA",
        "error": "#ba1a1a",
        "on-primary-container": "#cacfff",
        "on-secondary-fixed-variant": "#00497d",
        "primary-fixed": "#dee0ff",
        "success-available": "#28A745",
        "inverse-primary": "#bac3ff",
        "surface-container-low": "#f4f2fc",
        "tertiary-container": "#8f4700",
        "on-tertiary-fixed": "#301400",
        "surface-bright": "#fbf8ff",
        "info-assigned": "#17A2B8",
        "inverse-surface": "#2f3037"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "spacing-lg": "24px",
        "spacing-xl": "32px",
        "unit-base": "4px",
        "container-padding": "24px",
        "gutter": "16px",
        "spacing-sm": "8px",
        "spacing-xs": "4px",
        "spacing-md": "16px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "data-mono": ["Monospace"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}