spring:
  application:
    name: AssetTrack
  datasource:
    url: jdbc:postgresql://localhost:5432/assettrack
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: dummy_user
    password: dummy_password

jwt:
  issuer: assettrack-api

# RSA keys
rsa:
  private-key-location: ${RSA_PRIVATE_KEY_LOCATION:classpath:private_pkcs8.pem}
  public-key-location: ${RSA_PUBLIC_KEY_LOCATION:classpath:public.pem}
